### PR TITLE
Issue #81 - fix open welcome page

### LINKED ISSUE #81: Misc | Open welcome URL only when installing for the first time
The welcome screen (i.e. `MiscURLs.INSTALLED_URL`) should only be opened when installing the extension for the first time, instead of also being opened each time the extension is upgraded.

### PR DESCRIPTION
**Pull request by Saidmurod1996**
Fixes #81 

I couldn't reproduce the case Vasu told. Just made it open welcome page only installed for the first time

### CODE REVIEW

File: src/js/migration.js [hunk 1]
```diff
@@ -61,9 +61,6 @@ document.addEventListener("DOMContentLoaded", async function () {
 
   // Update contextual menu.
   chrome.runtime.sendMessage({ action: "updateContextualMenu" });
-
-  // Redirect to welcome URL.
-  window.open(MiscURLs.INSTALLED_URL, "_self");
```
Comment (jfmdev) [inline src/js/migration.js:66]: Beside don't opening the welcome screen you should close the current tab (otherwise the tab will show the "migrating" message indefinitely).

**Review by jfmdev — CHANGES_REQUESTED** [review]
The welcome screen is still being opened if the user upgrades from any version outside 4, like from 3.0 to 5.0 or from 5.0 to 5.1 (note the migration script is only run when upgrading from version `4.*`).

**Review by jfmdev — APPROVED** [review]

**Comment by tim-kodirov** [comment]
LGTM. The welcome screen is not being opened when version is changed
